### ISSUE TITLE
shape divider kill other option

### ISSUE THREAD

**Issue by micker** [Abhisheknanda1344463/grapesjs-shape-divider#1]
hello i try your plugin
before shape plugin
![image](https://user-images.githubusercontent.com/2539440/121884517-52abde00-cd13-11eb-8d29-11e5255d4bab.png)
we can see general option 

after divi shape plugin
alls options arn't display
![image](https://user-images.githubusercontent.com/2539440/121884423-31e38880-cd13-11eb-8f72-998d042fc2e9.png)
thanks for any help

**Comment by Abhisheknanda1344463** [comment]
Hi @micker 
because i've only set the "style options" Style manager sector for this plugin.

**Comment by micker** [comment]
hello @Abhisheknanda1344463 soory i don't understand the solution ?

**Comment by Abhisheknanda1344463** [comment]
@micker  If you go in the index file of style folder there you find that i've added some limited sector of styling for this plugin
